const https = require('https');
const { performance } = require('perf_hooks');

const MODEL_STYLES = {
    openai:   'photorealistic, ultra detailed, professional photography, 8K HDR',
    deepseek: 'digital art, futuristic cyberpunk, neon aesthetics, sharp lines, dark theme',
    meta:     'cinematic, dramatic IMAX lighting, epic widescreen composition, movie still',
    gemini:   'oil painting, impressionist masterpiece, vibrant colors, museum quality artwork',
};

function checkUrl(url) {
    return new Promise((resolve) => {
        const req = https.request(url, { method: 'HEAD', timeout: 12000 }, (res) => {
            resolve(res.statusCode < 400);
        });
        req.on('error', () => resolve(true)); // If HEAD fails, still return the URL
        req.on('timeout', () => { req.destroy(); resolve(true); });
        req.end();
    });
}

async function generateImagePollinations(prompt, modelKey) {
    const startTime = performance.now();
    try {
        const style = MODEL_STYLES[modelKey] || MODEL_STYLES.openai;
        const fullPrompt = `${prompt}, ${style}`;
        const seed = Math.floor(Math.random() * 999999);
        const encodedPrompt = encodeURIComponent(fullPrompt);
        const imageUrl = `https://image.pollinations.ai/prompt/${encodedPrompt}?model=flux&seed=${seed}&width=1024&height=1024&nologo=true`;
        
        await checkUrl(imageUrl);
        
        const time = Math.round(performance.now() - startTime);
        return {
            text: `![Generated by ${modelKey} — ${prompt}](${imageUrl})`,
            imageUrl,
            time,
            tokens: 80,
            status: "success",
            isImage: true
        };
    } catch (error) {
        console.error(`Pollinations Error (${modelKey}):`, error.message);
        const time = Math.round(performance.now() - startTime);
        return { text: `Image generation failed: ${error.message}`, time, tokens: 0, status: "error" };
    }
}

module.exports = { generateImagePollinations };
